### ISSUE TITLE
Stopped working on Azure?

### ISSUE THREAD

**Issue by XzaR90** [peters/xps2img#8]
As title say I think this has stopped working in Azure Web Apps since somewhere around 2017-11-10?

Can anyone confirm? It did work before now I just get a transparent/blank image with png.

**Comment by dougkl** [comment]
Yes, same problem here too

**Comment by XzaR90** [comment]
Hello I don't know the status but I have confirmed that this issue has to do with a newer App Service version and Microsoft is or was working on it.

**Comment by XzaR90** [comment]
I have confirmed it is working again.
